### ISSUE TITLE
set handler severity

### ISSUE THREAD

**Issue by dmpopoff** [otter18/tg_logger#3]
Hello!
I have used your library as another handler. 
```
    handler_n1.setLevel(logging.INFO)
    handler_n2.setLevel(logging.DEBUG)
    handler_n3.setLevel(logging.DEBUG)
    my_logger.addHandler(handler_n1)
    my_logger.addHandler(handler_n2)
    my_logger.addHandler(handler_n3)
    tg_logger.setup(my_logger, token=token, users=[chat_id])
```
For existing handlers, I set the level in the standard way. Please tell me how to set the level for your handler?

**Comment by alexvoksa** [comment]
> Hello! I have used your library as another handler.
> 
> ```
>     handler_n1.setLevel(logging.INFO)
>     handler_n2.setLevel(logging.DEBUG)
>     handler_n3.setLevel(logging.DEBUG)
>     my_logger.addHandler(handler_n1)
>     my_logger.addHandler(handler_n2)
>     my_logger.addHandler(handler_n3)
>     tg_logger.setup(my_logger, token=token, users=[chat_id])
> ```
> 
> For existing handlers, I set the level in the standard way. Please tell me how to set the level for your handler?

Hello! You can set logging level in standard way for these handlers, for example

`logger = logging.getLogger()
t_handler = TelegramHandler(channel_id=TELEGRAM_CHANNEL_ID, token=TELEGRAM_TOKEN)
t_handler.setLevel(logging.WARNING)
logger.addHandler(t_handler)`

**Comment by dmpopoff** [comment]
Hello! Thanks for a quick reply!
But according to documentation, the way to use this handler is:
`tg_logger.setup(my_logger, token=token, users=[chat_id])`
where is no description how to tune telegram handler **_before_** link it to my logger.

**Comment by dmpopoff** [comment]
if where is a way to identify this handler in set of logger.handlers I can set the level in a way like this:
logger.handlers[xxx].setLevel(logging.WARNING)
but how I can identifiy exactly this telegram handler?

**Comment by otter18** [comment]
Hello.
I've added some changes to the library, so now you can access handler, that is linked to your logger

```python
import logging
import tg_logger

# Telegram data
token = "1234567890:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
users = [1111111111]

# Base logger
logger = logging.getLogger('foo')
logger.setLevel(logging.INFO)

# Logging bridge setup
handler = tg_logger.setup(logger, token=token, users=users)

# Setting extra params
handler.setLevel(logging.DEBUG)

# Test
logger.info("Hello from tg_logger by otter18")
```

It is [beta version](https://github.com/otter18/tg_logger/releases/tag/v3.2-beta) for now, but you can install it from https://test.pypi.org/project/tg-logger/3.2/

**Comment by dmpopoff** [comment]
for future requesters, this works:
`pip install -i https://test.pypi.org/pypi/ --extra-index-url https://pypi.org/simple tg-logger`

setting individual loglevel for tghandler works like a charm.
