### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by dmpopoff** [otter18/tg_logger#5]
Hello!
Do you really need  pyTelegramBotAPI==3.7.6 exactly?
Or you can use  pyTelegramBotAPI>=3.7.6 requirement?
I use in my project latest pyTelegramBotAPI and your module version 3.2 (beta). If you don't have a clear reason to use the exact version of pyTelegramBotAPI, please update your dependency usage to use the wider versioning options.
Thanks!

**Comment by otter18** [comment]
Fixed in [v3.3](https://github.com/otter18/tg_logger/releases/tag/v3.3)

Thank for patience.
